name: Generate

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    generate:
        strategy:
            fail-fast: false
            matrix:
                file:
                    - app.php
                    - auth.php
                    - broadcasting.php
                    - cache.php
                    - cors.php
                    - database.php
                    - filesystems.php
                    - hashing.php
                    - logging.php
                    - mail.php
                    - queue.php
                    - sanctum.php
                    - services.php
                    - session.php
                    - view.php

        name: Generate ${{ matrix.file }} fluent Config
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            -   run: bin/punchcard https://raw.githubusercontent.com/laravel/laravel/10.x/config/${{ matrix.file }} --output generated --ansi

            # setup github user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"

            -
                name: "Tag Downgraded Code"
                run: |
                    # separate a "git add" to add untracked (new) files too
                    git add --all
                    git commit -m "release Generated Configs"

                    # force push tag, so there is only 1 version
                    git tag "${GITHUB_REF#refs/tags/}" --force
                    git push origin "${GITHUB_REF#refs/tags/}" --force
