name: Generate

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    generate:
        strategy:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none


            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            # create local version of laravel skeleton
            -   run: composer create-project laravel/laravel tmp-laravel --no-install --no-scripts

            # generate all configs
            -   run: bin/punchcard tmp-laravel/config --output generated

            # lint generated configs - must be valid PHP
            -   run: vendor/bin/parallel-lint generated
