name: Generate Release

on:
    push:
        tags:
            # avoid infinite looping, skip tags that ends with ".72"
            # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-branches
            - '*'

jobs:
    generate_release:
        runs-on: ubuntu-latest

        steps:
            -   uses: "actions/checkout@v3"
                with:
                    token: ${{ secrets.WORKFLOWS_TOKEN }}

            -
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: 8.1
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            # create local version of laravel skeleton
            -   run: composer create-project laravel/laravel tmp-laravel

            # generate all configs
            -   run: bin/punchcard tmp-laravel/config --output generated

            # setup git user
            -
                run: |
                    git config user.email "action@github.com"
                    git config user.name "GitHub Action"
            # publish to the same repository with a new tag
            # see https://tomasvotruba.com/blog/how-to-release-php-81-and-72-package-in-the-same-repository/
            -
                name: "Tag Downgraded Code"
                run: |
                    # separate a "git add" to add untracked (new) files too
                    git add --all
                    git commit -m "release Generated Configs"

                    # force push tag, so there is only 1 version
                    git tag "${GITHUB_REF#refs/tags/}" --force
                    git push origin "${GITHUB_REF#refs/tags/}" --force
